import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Shield, X, AlertTriangle, ExternalLink } from "lucide-react";

interface ArtifactWarningProps {
  /** Where the banner appears: 'report' for generated reports, 'global' for app-wide */
  variant?: "report" | "global" | "export";
  /** Allow dismissal */
  dismissible?: boolean;
  /** Custom classification text */
  classification?: string;
}

export function ArtifactWarning({
  variant = "global",
  dismissible = true,
  classification = "UNCLASSIFIED // PUBLIC DATA ONLY",
}: ArtifactWarningProps) {
  const [dismissed, setDismissed] = useState(false);

  if (dismissed) return null;

  const messages = {
    global: {
      title: "OSINT GOVERNANCE NOTICE",
      body: "This platform operates exclusively on publicly available data sources. All intelligence products are generated from open-source information and should be independently verified before operational use.",
      icon: Shield,
    },
    report: {
      title: "ARTIFACT WARNING",
      body: "This product was generated by an AI-assisted OSINT platform using publicly available data sources only. It does not contain classified, proprietary, or unlawfully obtained information. All findings require independent verification.",
      icon: AlertTriangle,
    },
    export: {
      title: "EXPORT NOTICE",
      body: "This export contains intelligence derived from public data sources. Chain of custody and provenance metadata are included. Verify all claims independently before dissemination.",
      icon: AlertTriangle,
    },
  };

  const msg = messages[variant];
  const Icon = msg.icon;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: -10 }}
        className={`
          relative border rounded-lg p-3 mb-4
          ${variant === "report"
            ? "bg-amber-500/10 border-amber-500/30 text-amber-200"
            : variant === "export"
              ? "bg-orange-500/10 border-orange-500/30 text-orange-200"
              : "bg-cyan-500/5 border-cyan-500/20 text-cyan-300/80"
          }
        `}
      >
        <div className="flex items-start gap-3">
          <Icon className="w-5 h-5 mt-0.5 flex-shrink-0 opacity-80" />
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs font-mono font-bold tracking-wider opacity-90">
                {msg.title}
              </span>
              <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-current/10 opacity-60">
                {classification}
              </span>
            </div>
            <p className="text-xs leading-relaxed opacity-70">
              {msg.body}
            </p>
          </div>
          {dismissible && (
            <button
              onClick={() => setDismissed(true)}
              className="p-1 rounded hover:bg-white/10 transition-colors opacity-50 hover:opacity-100"
              aria-label="Dismiss notice"
            >
              <X className="w-3.5 h-3.5" />
            </button>
          )}
        </div>
      </motion.div>
    </AnimatePresence>
  );
}

/**
 * Inline attestation footer for reports and exports.
 * Non-dismissible, compact.
 */
export function AttestationFooter() {
  return (
    <div className="mt-6 pt-4 border-t border-cyan-500/20">
      <div className="flex items-center gap-2 text-[10px] font-mono text-cyan-400/50">
        <Shield className="w-3 h-3" />
        <span>EMPIRE DASHBOARD v3.0</span>
        <span className="opacity-50">|</span>
        <span>UNCLASSIFIED // PUBLIC DATA ONLY</span>
        <span className="opacity-50">|</span>
        <span>Generated: {new Date().toISOString()}</span>
      </div>
      <p className="text-[9px] font-mono text-cyan-400/30 mt-1 leading-relaxed">
        This product was generated from publicly available data sources.
        All information should be independently verified. No classified,
        proprietary, or unlawfully obtained data is included.
        Immutable audit trail with SHA-256 hash chain verification available.
      </p>
    </div>
  );
}

export default ArtifactWarning;
